# dataset and data loader settings
datasets:
  name: Flare7Kpp
  type: Flare7kpp_Pair_Loader
  image_path: ./data/flare7kpp/Flickr24K
  scattering_dict:
    Flare7k_scattering: ./data/flare7kpp/Flare7K/Scattering_Flare/Compound_Flare
    Real_scattering1: ./data/flare7kpp/Flare-R/Compound_Flare
  reflective_dict: 
    Flare7k_reflective: ./data/flare7kpp/Flare7K/Reflective_Flare
    Real_reflective1: ~
  light_dict:
    Flare7k_light: ./data/flare7kpp/Flare7K/Scattering_Flare/Light_Source
    Real_light1: ./data/flare7kpp/Flare-R/Light_Source
  data_ratio: [0.5, 0.5] # or [0.6, 0.4], only a ratio is enough
  transform_base:
    img_size: 512
  transform_flare:
    scale_min: 0.8
    scale_max: 1.2
    translate: 300
    shear: 20
  mask_type: "light"

  
  # data loader
  use_shuffle: true
  num_worker_per_gpu: 4
  batch_size_per_gpu: 2
  dataset_enlarge_ratio: 1
  prefetch_mode: ~

testing_dataset:
  name: flare_test
  type: Image_Pair_Loader
  dataroot_gt: ./data/flare7kpp/test_data/real/gt
  dataroot_lq: ./data/flare7kpp/test_data/real/input
  dataroot_mask: ./data/flare7kpp/test_data/real/mask
  gt_size: 512